- name: set swarm node to drain availability
  ansible.builtin.command: docker node update --availability drain {{ inventory_hostname }}

- name: stop docker daemon
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: true

- name: stop docker.socket daemon
  ansible.builtin.systemd:
    name: docker.socket
    state: stopped
    enabled: true

- name: install dnf updates
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: reboot
  ansible.builtin.reboot:

- name: set swarm node to active availability
  ansible.builtin.command: docker node update --availability active {{ inventory_hostname }}
